### ISSUE TITLE
Add mission timeouts

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#113]

**Comment by mattlangford** [comment]
I can include this in my next PR

**Comment by jpanikulam** [comment]
Perfect

**Comment by jpanikulam** [comment]
@mattlangford Did we ever land on this?

**Comment by mattlangford** [comment]
No reply from @forrestv yet. What do?

**Comment by jpanikulam** [comment]
Have you tried emailing god-president Trump?

**Comment by jpanikulam** [comment]
I couldn't find the timeout code on your fork, did you remove it? I was going to clone and try

**Comment by mattlangford** [comment]
I did remove it. I can add it back tonight.

**Comment by forrestv** [comment]
> No reply from @forrestv yet. What do?

Huh? Not sure what you mean. Are you waiting on me fixing the spurious traceback that is printed in the case you emailed me? I thought it wasn't blocking any progress..?

**Comment by mattlangford** [comment]
Hmm I guess you're right. It doesn't actually break anything, no reason to fret over it.

**Comment by forrestv** [comment]
Well, I'm definitely going to look into it. I just wanted to point out that
it shouldn't prevent you from advancing.

I'm still a bit confused, though: that issue you showed me, I wonder why I
never saw it before when I was writing missions... From the script you
showed me, it didn't look like you were doing anything unusual... I have to
try to replicate it locally.

FYI, also, I'm likely going to redo the txros action API. It's a mess right
now.

**Comment by mattlangford** [comment]
@jpanikulam, have you tried running it yet? I wonder if it's just a weird issue on my machine. I haven't ran it anywhere else.

Happy birthday by the way Forrest

**Comment by kev-the-dev** [comment]
Will be done via #320
