### ISSUE TITLE
CNN for object recogntion

### ISSUE THREAD

**Issue by LucasBA** [uf-mil/SubjuGator#128]

**Comment by LucasBA** [comment]
I tried to assign myself but I think I don't have authority.

**Comment by mattlangford** [comment]
**GET 'ER DONE**

**Comment by rleyva** [comment]
We should probably sit down and collect images for all of the possible classes instead of wasting time and making our own individual sets

**Comment by sentree** [comment]
This issue seems to be irrelevant and outdated, can it be closed?

**Comment by LucasBA** [comment]
irrelevant and outdated
