### ISSUE TITLE
command-line switch to run Gazebo without cameras/GUI

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#130]
Controller testing is cumbersome with cameras and GUI running. 

Esp with Jason in CA, having no access to AWS or MIL-JOHNNY5

**Comment by jpanikulam** [comment]
@mattlangford if you find time

**Comment by mattlangford** [comment]
I don't think this will be a problem

**Comment by mattlangford** [comment]
To do*
