### ISSUE TITLE
INSTALL: Add twisted and socat to install script

### ISSUE THREAD

**Issue by rleyva** [uf-mil/SubjuGator#154]

**Comment by rleyva** [comment]
Also, service_identity (python module)

**Comment by rleyva** [comment]
Along with pyasn1 and characteristic, also python modules

**Comment by sentree** [comment]
I will also add screen to the list of dependencies, we need it to run the roscore at startup

**Comment by rleyva** [comment]
Sounds good!

**Comment by sentree** [comment]
I included the crc16 library as requested by @mattlangford 

All of these will be included in my next pull request, so this issue is resolved and can be closed
