### ISSUE TITLE
ML: Store "observe" function/kernels along with classifiers

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#155]
Right now, if someone modifies features.py after a classifier is trained, the classifier simply won't work anymore

**Comment by mattlangford** [comment]
You right, you think just appending the list of features to the classifer pickle will work?

**Comment by jpanikulam** [comment]
I think so. ought to make a unified `observe` to make sure there's no goof-ups. 

Also, Boosting can tell you which kernels are being useful, so you could save convolutions by selectively using only the ones that help

**Comment by mattlangford** [comment]
Did you want to do that? I can possibly tonight after I do some testing depending on how late it is when I finish what I'm working on rn

**Comment by mattlangford** [comment]
Also do you think it might be good to save the cv2 classifiers in a pickle as well vs using an xml which it does now? That would make switching between the two really simple. Esp if we wanting to include other things in the pickle like kernels

**Comment by jpanikulam** [comment]
All you, my friend. 

Unfortunately, cv2 classifiers can't be pickled, because they are made as Boost::Python bindings, so we have to use their serialization interface

**Comment by mattlangford** [comment]
Ohh the data doesn't exist in the python world.
I guess you could pickle the xml somehow

**Comment by jpanikulam** [comment]
I'm not sure it would be worth the investment of effort, but...
I think you could come up with a trick where you write it to /dev/stdin, [grab it](http://stackoverflow.com/questions/1450393/how-do-you-read-from-stdin-in-python), then pickle that...and then when you read it, you read from /dev/stdout

or something ridiculous like that

**Comment by mattlangford** [comment]
I'm just trying to figure out a good way to save an arbitrary learning object that can be used by this theoretical interface.
