### ISSUE TITLE
Cant build repo on 16.04 with ROS Kinetic

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#182]
It seems like right now the one thing stopping us is broken macros in manifold.h form rawgps-tools. 

@forrestv any ideas for quick fixes? Or should we just mess around with fixing the macros using the updated boost version?

**Comment by kev-the-dev** [comment]
It is building now right? Would it be possible to add/change the semaphore to 16.04 to reflect our transition?

**Comment by DSsoto** [comment]
**UPDATE:** @forrestv patched the rawgps_tools pkg so it would build on 16.04. I fixed the sub8_perception pkg so it would build on the more recent g++ version. Repo builds on 16.04 now.

@ironmig we should definitely do that. Do you want to?
