### ISSUE TITLE
Kalman filter needs to know where it is

### ISSUE THREAD

**Issue by forrestv** [uf-mil/SubjuGator#187]
`Sub8/command/sub8_launch/launch/subsystems/odometry.launch` needs to have its location set to Gainesville (`_start_x_ecef:=738543 _start_y_ecef:=-5498316 _start_z_ecef:=3136465`) for testing in Gainesville (and San Diego when in San Diego).

Otherwise, north won't correspond to true north ... not a huge loss, but something to take note of.

**Comment by DSsoto** [comment]
Will add this to the launch file.

**Comment by DSsoto** [comment]
Fixed in #188
