### ISSUE TITLE
Remove packages migrated to mil_common

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#205]
We should start removing duplicate packages in the repo.

This is some of what needs to go:
+ sub8_perception/*/sub8_vision_lib
+ sub8_sonar
+ hydrophones
+ paulboard
+ some of sub8_tools
+ some of sub8_msgs

Be sure to reference your PR if you do any of this and/or add to this list.

**Comment by sentree** [comment]
Is taking care of this on NaviGator right now out of the question? I feel like if we don't it will be a mess to do next year.

**Comment by sentree** [comment]
Also, I would advise that we merge [mil_common #15](https://github.com/uf-mil/mil_common/pull/15) before this.

**Comment by DSsoto** [comment]
Only if it's a low effort thing, we don't want to sink a lot of time into making NaviGator compatible right now.

Have you even reviewed any of it or commented that it looks good? No one has.

**Comment by kev-the-dev** [comment]
I'm going to make this my pet project for the week. Plan is as follows:

1. Remove packages/files duplicated in mil_common
1. [Use git grep with awk](http://blog.jasonmeridth.com/posts/use-git-grep-to-replace-strings-in-files-in-your-git-repository/) to replace strings like 'sub8_ros_tools' with 'mil_ros_tools'
1. Look at diff to verify nothing crazy happened
1. Start testing things to see what's broken

I'll open a PR once I get to step 4 to see if anyone notices anything wacky.

**Comment by sentree** [comment]
Can this be closed now that #216 has been merged?
