### ISSUE TITLE
Set reasonable white balance defaults

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#207]
The point grey camera drivers do some sort of optimization procedure for white balancing, the settings can be very dynamic and not settle for a while.

Sometimes, the algorithm fails to set reasonable settings when there is not enough variety of color in view.

We need to figure out how to set the cameras up to start the adjusting process from settings we know are reasonable in the water.

**Comment by duggerdufl** [comment]
It's not just us - https://github.com/ros-drivers/pointgrey_camera_driver/issues/55

**Comment by kev-the-dev** [comment]
Unnecessary after switch to Seecam cameras, which provide sufficient auto white balance on hardware
