### ISSUE TITLE
Script to update mil_ws on the vehicle

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#239]
It is very easy to forget to pull the latest code from one of our master branches into the sub.

A script should be made to automate this, so it's one less thing to worry about before pool days.

It should do the following:
* Rename `SubjuGator` and `mil_common` to `<repo_name>_<current_date>` (only repos in mil_ws)
* Clone the latest mil_common and SubjuGator repos
* Print out the HEAD commit hashes of all of the newly cloned repositories (including submodules)

**Comment by sentree** [comment]
This should be fairly simple, I will add `-p` and `--pull` flags to wsmux.

**Comment by sentree** [comment]
This was added in uf-mil/mil_common#54.
