### ISSUE TITLE
Create buoy detection ROS service

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#241]
We need to have a ROS service that takes as input a buoy type and a rectified color image and returns either a binary segmentation of that specific buoy in the image or the image coordinates of the center of the buoy in that frame, and the specific camera info (time, frame_id) for the frame that was used.

It should also have a way of reporting that the buoy could not be found, and it would be great if we had a way of returning a confidence level in the segmentation or centroid calculation.

@aaron-iglesias we need to start working on the infrastructure for your perception so we can actually start testing at the pool and in gazebo.

**Comment by DSsoto** [comment]
@aaron-iglesias can you try to get a basic vision proxy (perception node) running to test this Saturday on the sub?

**Comment by sentree** [comment]
Should we consider this complete since @ironmig's mission seems to work well?

**Comment by kev-the-dev** [comment]
Closing dead issue, no longer relevant
