### ISSUE TITLE
Chain Sequence of Pose Commands

### ISSUE THREAD

**Issue by LucasBA** [uf-mil/SubjuGator#245]
Mechanism for giving the sub a list of pose commands to achieve from the command line and from the mission runner.

**Comment by mattlangford** [comment]
C3 will accept velocity only waypoints, this can be used to go in one direction without slowing down at the end. You'd just need to track the subs position and switch the waypoint at some point to get it to move where you want.

**Comment by DSsoto** [comment]
This is dealt with in #249
