### ISSUE TITLE
Make path_marker_finder generic

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/SubjuGator#253]
The competition requires finding the pose of multiple bright orange polygons objects repeatedly.

Kevin has implemented this successfully for the path marker (#229) but there is no reason to not use it for the bin lids as well.

I propose changing the name of the perception code from `path_marker_finder` to `orange_rectangle_finder` or some other more generic name. It should have a /set_geometry service that allows you to set the width and height of the object you want to find the pose of.

**Comment by sentree** [comment]
I can look in to this if @ironmig doesn't want to since I will be handling this part of the perception for the bins challenge anyway.

**Comment by kev-the-dev** [comment]
I got this. Already doing that so it can work with unit tests
