### ISSUE TITLE
Add checkpoints to Gazebo

### ISSUE THREAD

**Issue by Grymessa** [uf-mil/SubjuGator#270]
We need to add locations in the sim that when prompted in the console can teleport the sub in front of each objective. Currently, we have to maneuver to each objective prop. 

- [x] Nav Gate Waypoint
- [x] Start Gate Waypoint
- [x] Bin Waypoint
- [x] Octogon Waypoint
- [x] Torpedo Board Waypoint
- [x] Buoy Waypoint

**Comment by DSsoto** [comment]
I'd recommend having a yaml under sub8_gazebbo/config with named world frame poses. Keep in mind that there is a difference between the map frame and  the world frame (the origin of the map frame is dependent on where the sub is spawned while the world frame is independent).

This will be great for integrating gazebo tests into CI.

**Comment by sentree** [comment]
This is definitely a good idea, but I would recommend also looking into a way to generate custom worlds. For example, place a start gate at x1, y1, z1, p1, r1, y1 and the sub at x2, y2, z2, p2, r2, y2. This will be ideal for use with both a Monte Carlo testing engine as well as user-defined unit tests.

**Comment by DSsoto** [comment]
Sure, but let's do things incrementally. I think this is something he could get done relatively quickly.

**Comment by DSsoto** [comment]
@Grymestone addressed everything in #276.
