### ISSUE TITLE
Make tools for easily testing changes to vision

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#86]

**Comment by rleyva** [comment]
What exactly do you envision for this?

**Comment by jpanikulam** [comment]
On segmented/labelled bags

Bare minimum:
Test that we detect the objects' **centroid** correctly in 2D 90% of the time

Gold:
Test that we get a good **segmentation** in 2D 90% of the time

Platinum:
Test that our **3D** pose estimate is close 90% of the time. Platinum because it probably means we have to do 3D labelling.

**Comment by LucasBA** [comment]
Would a bounding box suffice for gold?

**Comment by jpanikulam** [comment]
I think a bounding box would be most of the way to gold. If we are going all-in on CNN's, I'd call it equivalent.

**Comment by kev-the-dev** [comment]
Moving to uf-mil/mil_common#31
