### ISSUE TITLE
Get a PPA working (Or some solution for distributing binaries)

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#89]
- In the short term, everyone is going to have to compile PCL from source

**Comment by jpanikulam** [comment]
Interim solution: Going to make everyone compile pcl from source.

**Comment by sentree** [comment]
I will be trying to download, build, package, and distribute the following in the next few weeks:
- OMPL (current)
- PCL (1.8)
- ArrayFire (current)
- OpenCV (2.4.13 -cuda -opencl -mp)
- Ceres (current)
- gpu-voxels (current)

If anyone has any additions or suggestions as to how to best build these, please comment below. I will be building for amd64, i386, and arm (where possible) platforms.

**Comment by sentree** [comment]
Since the move to Ubuntu 16.04 and ROS Kinetic, I think all of the dependency version issues we were having have been resolved. Can anyone confirm whether or not we still need any of the binaries listed above to be custom compiled?

**Comment by sentree** [comment]
Please close this due to lack of activity.
